### ISSUE TITLE
Allgemein

### ISSUE THREAD

**Issue by limper545** [programina-gui/landlord-calendar#8]
Bitte nicht alles falsch verstehen, das bedeutet nicht das der Code schlecht ist, der ist gut.

Aber wenn du bereit bist dich richtig in Angular einzuarbeiten, dann direkt richtig. Keine halben Sachen. 

Irgendwelche Angular Tutorials das können auch Inder für den halben Preis.

Aber so Sachen wie:

Jeder Observer hat ein $ am Ende. Da sieht jemand mit Erfahrung direkt: Die Person hat Ahnung was er tut.
Oder auch die Architektur 

Und für sowas steht Avameo :D :D :D

**Comment by programina-gui** [comment]
:) ... Es müsste ein Schleichwerbung-Emoji geben. ;) Danke für den Tipp.
